name: pubm
description: A command-line application to manage pubspec dependencies.
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  # normal dependencies
  args: ^2.4.2
  cli_util: ^0.4.0
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  json2yaml: ^3.0.1
  path: ^1.8.0
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # normal dependencies
  lints: ^2.1.1

flutter:
  uses-material-design: true
  generate: true
