name: abc
description: A new Flutter project.
version: 2.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: 3.3.10

dependencies:
  # git related dependencies
  sticky_grouped_list:
    git:
      url: 'ssh://git@github.com/abc/sticky_grouped_list.git'
      ref: develop
  # path related dependencies
  alice:
    path: packages/alice
  # normal dependencies
  analyzer: ^5.12.0
  archive: ^3.3.0
  async: ^2.9.0
  audioplayers: ^4.0.1
  bloc: ^8.1.2
  blurhash_dart: ^1.1.0
  bot_toast: ^4.0.3
  carousel_slider: ^4.1.1
  collection: ^1.16.0
  connectivity_plus: ^3.0.3
  convert: ^3.1.1
  crypto: ^3.0.2
  cupertino_icons: ^1.0.2
  desktop_drop: ^0.4.0
  device_info_plus: ^9.0.2
  disable_battery_optimization: ^1.1.0+1
  equatable: ^2.0.5
  fake_async: ^1.3.1
  fast_cached_network_image: ^1.1.1
  ffmpeg_kit_flutter_min_gpl: ^5.1.0
  file_picker: ^5.2.1
  flutter_apns_only: ^1.6.0
  flutter_background_service: ^2.4.5
  flutter_background_service_android: ^3.0.3
  flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^8.1.3
  flutter_blurhash: ^0.7.0
  flutter_cache_manager: ^3.3.0
  flutter_emoji: ^2.4.0
  flutter_foreground_task: ^4.0.1
  flutter_local_notifications: ^12.0.4
  flutter_ringtone_player: ^3.2.0
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.5
  flutter_webrtc: ^0.9.20
  hive: ^2.2.3
  http: ^0.13.5
  image: ^3.3.0
  image_picker: ^0.8.6
  intl: ^0.18.0
  log_4_dart_2: ^1.0.0-rc.1
  modal_bottom_sheet: ^2.1.2
  native_imaging: ^0.1.0
  open_filex: ^4.3.1
  package_info_plus: ^4.0.0
  pasteboard: ^0.2.0
  path: ^1.8.2
  path_provider: ^2.0.11
  photo_view: ^0.14.0
  provider: ^6.0.4
  qr_flutter: 4.0.0
  queue: ^3.1.0+2
  record: ^4.4.1
  rxdart: ^0.27.5
  sentry: ^7.6.2
  sentry_flutter: ^7.6.2
  share_plus: ^7.0.0
  shared_preferences: ^2.0.15
  thumblr: ^0.0.4
  tuple: ^2.0.1
  url_launcher: ^6.1.10
  uuid: ^3.0.7
  video_thumbnail: ^0.5.3
  wakelock: ^0.6.2
  webrtc_interface: ^1.0.10
  webview_flutter: ^3.0.4
  wechat_assets_picker: ^8.5.0
  window_manager: ^0.3.1

dev_dependencies:
  # git related dependencies
  olm:
    git:
      url: 'ssh://git@github.com/abc/olm.git'
      ref: develop
  # normal dependencies
  appium_driver: ^0.6.0
  bloc_test: ^9.1.3
  build_runner: ^2.3.0
  flutter_launcher_icons: any
  flutter_lints: ^2.0.0
  mason: any
  mockito: ^5.3.2
  test: any

dependency_overrides:
  # git related dependencies
  wakelock_windows:
    git:
      url: https://github.com/timsneath/wakelock.git
      ref: 2a9bca63a540771f241d688562351482b2cf234c
      path: wakelock_windows
  # normal dependencies
  analyzer: ^5.12.0
  image: ^3.3.0
  intl: ^0.18.0
  matcher: ^0.12.16
  webrtc_interface: ^1.0.11

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/common/
    - assets/images/themes/
    - assets/app_icon/icon.png
    - assets/audio/
  generate: true
  fonts:
    - family: IconSet
      fonts:
        - asset: packages/abc/fonts/IconSet.ttf
    - family: Barlow
      fonts:
        - asset: packages/abc/fonts/Barlow-Bold.ttf
          weight: 700
        - asset: packages/abc/fonts/Barlow-SemiBold.ttf
          weight: 600
        - asset: packages/abc/fonts/Barlow-Medium.ttf
          weight: 500
        - asset: packages/abc/fonts/Barlow-Regular.ttf
          weight: 400
    - family: Cairo
      fonts:
        - asset: packages/abc/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: packages/abc/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: packages/abc/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: packages/abc/fonts/Cairo-Regular.ttf
          weight: 400
