name: Commit Push

on:
  pull_request: 
  push:
    branches:
      - '*'
  

permissions:
  contents: read
  issues: write
  pull-requests: write
  discussions: write

jobs:

  check-branch:
    runs-on: ubuntu-latest
    name: Check branch
    steps:
      - uses: actions/checkout@v2
      - name: Cache Flutter SDK
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: flutter-sdk-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            flutter-sdk-${{ runner.os }}-
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version

      - name: Install dependencies
        run: dart pub get

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: dart test

      - name: Run dart publish (dry run)
        if: ${{ github.event.pull_request.base.ref == 'main' }}
        run: dart pub publish --dry-run
