name: Build Release

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  create-tag:
    permissions:
      repository-projects: write
      packages: write
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get version
        id: yq
        uses: mikefarah/yq@master

        with:
          cmd: yq -r '.version' 'pubspec.yaml'

      - name: Print version
        run: echo ${{ steps.yq.outputs.result }}

      - name: Create tag
        uses: actions/github-script@v3
        id: "tag_create"
        env:
          TAG: ${{ steps.yq.outputs.result }}
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
             ref: "refs/tags/${{ steps.yq.outputs.result }}",
              sha: context.sha
            })

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.yq.outputs.result }}
          token: ${{ secrets.GITHUB_TOKEN }}
        

    
    

