name: Trigger Create Tag and Publish Workflow on PR Merge

on:
  pull_request:
    types:
      - closed
  # workflow_call:
  #   secrets:
  #     TRIGGER_CREATE_TAG_AND_PUBLISH: 
  #       required: true
  #       description: |
  #         Set to true to trigger the Create Tag and Publish workflow.
  #         Set to false to not trigger the Create Tag and Publish workflow.
  #         Set to anything else to not trigger the Create Tag and Publish workflow.

  

jobs:
  trigger-create-tag-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is merged into main
        id: check_merged
        run: |
          if [ "${{ github.event.pull_request.merged }}" = "true" ] && [ "${{ github.event.pull_request.base.ref }}" = "main" ]; then
            echo "true"
          else
            echo "false"
          fi

      - name: Set trigger_create_tag_and_publish output
        id: set_output
        run: echo "set-env:TRIGGER_CREATE_TAG_AND_PUBLISH=${{ steps.check_merged.outputs.result}}" >> $GITHUB_ENV
        env:
          TRIGGER_CREATE_TAG_AND_PUBLISH: ${{ steps.check_merged.outputs.result}}
      
      - name: Trigger dependent workflow
        run: |
            if [ "${{ steps.check_merged.outputs.result }}" = "true" ]; then
              curl -X POST \
                -H "Accept: application/vnd.github.v3+json" \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                https://api.github.com/repos/${{ github.repository }}/actions/workflows/create_tag.yml/dispatches \
                -d '{"ref": "main"}'
            fi
          
       